AWSTemplateFormatVersion: 2010-09-09
Description: A Template with VPC, Subnet, EC2 Instance, and EBS Volume

Parameters:
  EnvType:
    Description: Choose the environment type (prod or test).
    Type: String
    Default: test
    AllowedValues:
      - prod
      - test
    ConstraintDescription: Must specify prod or test.

  VPCNameParameters:
    Description: Enter a name for the VPC (e.g., VPC001, VPC002).
    Type: String
    Default: VPC001
    AllowedValues:
      - VPC001
      - VPC002
      - VPC003
      - VPC004

  VPCCIDR:
    Description: Enter the IP range (CIDR Notation) for the VPC.
    Type: String
    Default: 10.0.0.0/16

  PublicSubnetCIDR:
    Description: CIDR block for the public subnet.
    Type: String
    Default: 10.0.1.0/24

  AvailabilityZone:
    Description: Availability zone for resources.
    Type: String
    Default: ap-south-1a

Conditions:
  CreateProdResources: !Equals
    - !Ref EnvType
    - prod

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VPCCIDR
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Ref VPCNameParameters

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: PublicGateway

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: PublicRouteTable

  PublicRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway
    DependsOn: AttachGateway

  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: !Ref PublicSubnetCIDR
      VpcId: !Ref VPC
      AvailabilityZone: !Ref AvailabilityZone
      Tags:
        - Key: Name
          Value: !Sub ${EnvType}-PublicSubnet

  SubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet
      RouteTableId: !Ref PublicRouteTable

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0b7207e48d1b6c06f
      SubnetId: !Ref PublicSubnet
      Tags:
        - Key: Name
          Value: Test-Instance

  NewVolume:
    Type: AWS::EC2::Volume
    Condition: CreateProdResources
    Properties:
      Size: 20
      AvailabilityZone: !GetAtt EC2Instance.Placement.AvailabilityZone
      Tags:
        - Key: Name
          Value: ProdVolume

  MountPoint:
    Type: AWS::EC2::VolumeAttachment
    Condition: CreateProdResources
    Properties:
      InstanceId: !Ref EC2Instance
      VolumeId: !Ref NewVolume
      Device: /dev/sdh

Outputs:
  VPCID:
    Description: VPC ID
    Value: !Ref VPC

  SubnetID:
    Description: Subnet ID
    Value: !Ref PublicSubnet

  EC2Instance:
    Description: EC2 Instance ID
    Value: !Ref EC2Instance

  EBSVolume:
    Description: EBS Volume ID (only for prod)
    Value: !If
      - CreateProdResources
      - !Ref NewVolume
      - No EBS Volume Created